with entry {
    watch_code_prompt =
        '\nI\'ve written your instructions in comments in the code and marked them with "ai"\nYou can see the "AI" comments shown below (marked with █).\nFind them in the code files I\'ve shared with you, and follow their instructions.\n\nAfter completing those instructions, also be sure to remove all the "AI" comments from the code too.\n';
    watch_ask_prompt =
        '/ask\nFind the "AI" comments below (marked with █) in the code files I\'ve shared with you.\nThey contain my questions that I need you to answer and other instructions for you.\n';
}